

#
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.url=jdbc:mysql:///vueblog?useUnicode=true&characterEncoding=UTF-8
#spring.datasource.username=username
#spring.datasource.password=password
#mybatis.config-location=classpath:/mybatis-config.xml
#
#server.port=8081
#logging.level.org.springframework.security=info
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  jackson:
    serialization.indent_output: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@10.203.104.131:1532:DV086
    username: OWIPOP
    password: aDFkNP6Y
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 8081
logging:
  level: info
mybatis:
  config-location: classpath:/mybatis-config.xml